// "use client";
import HomeNavigation from "@/components/navigation-bars/home-navigation-bar";
import "../globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "@/components/provider/theme-provider";
import HomeFooter from "@/components/navigation-bars/home-footer-bar";
import ProgressbarProviders from "@/components/provider/progress-bar-provider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Project Planit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link rel="shortcut icon" href="/logo.svg" />
      </head>
      <body className={poppins.className}>
        <ThemeProvider attribute="class" forcedTheme="theme-blue">
          <ProgressbarProviders>
            <div className="h-screen overflow-auto relative">
              <HomeNavigation />
              {children}
              <HomeFooter />
            </div>
          </ProgressbarProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
