"use client";

import "../globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "@/components/provider/theme-provider";
import PaymentNavbar from "@/components/navigation-bars/payment-nav-bar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

// export const metadata: Metadata = {
//   title: "Cart",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link rel="shortcut icon" href="/logo.svg" />
      </head>
      <body className={poppins.className}>
        <ThemeProvider attribute="class" forcedTheme="theme-blue">
          <div className="h-screen overflow-auto relative">
            <PaymentNavbar />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
