import AppSubsideBar from "@/components/navigation-bars/app-subside-bar";
import { CalendarDays } from "lucide-react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Teams",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex w-full h-full overflow-hidden">
      <AppSubsideBar title={"Team/projects"} icon={<CalendarDays />} />
      {children}
    </div>
  );
}
