import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import ProgressBar from "@/components/common/progressbar";
import { Toaster } from "@/components/ui/sonner";
import ReduxProvider from "@/components/providers/redux-provider";

const font = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project planit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="shortcut icon" href="/logo.svg" />
      </head>
      <body className={font.className}>
        <ReduxProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark-violet"
            themes={["light", "dark-violet"]}
            enableSystem
          >
            <ProgressBar />
            {children}
            <Toaster />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
