import AppSubsideBar from "@/components/navigation-bars/app-subside-bar";
import SettingsSubSideBar from "@/components/navigation-bars/settings-sub-side-bar";
import { CalendarDays } from "lucide-react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Settings",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex w-full h-full overflow-hidden">
      <SettingsSubSideBar />
      {children}
    </div>
  );
}
